image:
  name: node:12.16-slim
pages:
  stage: deploy
  only:
  - master
  cache:
    paths:
    - .cache
    - node_modules
  before_script:
  - npm install
  script:
  - npm generate
  artifacts:
    paths:
    - public
