image:
  name: antora/antora:2.3.0
pages:
  stage: deploy
  only:
  - master
  cache:
    paths:
    - .cache/
  script:
  - npm install asciidoctor-plantuml
  - antora --fetch --cache-dir=.cache/antora --to-dir=public antora-playbook.yml
  artifacts:
    paths:
    - public/
