site:
  title: Antora Examples
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://ueisele-playground.gitlab.io/doc-antora-single
  start_page: antora-examples::index.adoc
content:
  sources:
  - url: ./
    start_path: docs
    branches: [HEAD]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    sectanchors: true
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki