:toc:
:toc-title:
:sectnums:
:toclevels: 3

:antora_version: 2.3

= PlantUML

It's possible to generate diagrams and flowcharts from text in Antora using link:https://plantuml.com/[PlantUML].

PlantUML is a component that allows to quickly write diagrams using a simple and intuitive textual language.
The textual language in which diagrams can be defined is also called PlantUML (see link:https://plantuml.com/guide[PlantUML Language Reference Guide]).

If you're new to using PlantUML or need help identifying issues in your PlantUML code, the link:http://plantuml.com/plantuml/[PlantUML Live Editor] is a helpful tool for creating and resolving issues within PlantUML diagrams.

TIP: PlantUML supports not only UML diagram types, but also other link:https://plantuml.com/en/[diagram types] like Gantt and Mindmap.

TIP: Besides PlantUML specific textual descriptions, PlantUML supports also link:https://www.graphviz.org/[Graphviz (DOT)] and link:http://ditaa.sourceforge.net/[Ditaa].

== Integration

=== Antora

Integration of PlantUML in Antora is achievied by xref:diagrams/extensions/kroki.adoc[Kroki] or xref:diagrams/extensions/plantuml.adoc[PlantUML] extension.

In order to generate a diagram or flowchart, you should write your text inside the `plantuml` block.

=== VSCode

VSCode can render PlantUML in AsciiDoc with the VSCode link:https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[AsciiDoc extension] and a configured xref:diagrams/extensions/kroki.adoc#_vscode[Kroki server] or xref:diagrams/extensions/plantuml.adoc#_vscode[PlantUML server].

== Diagram Types

=== PlantUML

==== Sequence Diagram

A link:https://plantuml.com/en/sequence-diagram[sequence diagram] shows object interactions arranged in time sequence. 

[source,asciidoc]
....
[plantuml]
----
participant User

User -> A: DoWork
activate A #FFBBBB

A -> A: Internal call
activate A #DarkSalmon

A -> B: << createRequest >>
activate B

B --> A: RequestCreated
deactivate B
deactivate A
A -> User: Done
deactivate A
----
....

[plantuml]
----
participant User

User -> A: DoWork
activate A #FFBBBB

A -> A: Internal call
activate A #DarkSalmon

A -> B: << createRequest >>
activate B

B --> A: RequestCreated
deactivate B
deactivate A
A -> User: Done
deactivate A
----

The keyword `autonumber` is used to automatically add number to messages.

[source,asciidoc]
....
[plantuml]
----
autonumber
Bob -> Alice : Authentication Request
Bob <- Alice : Authentication Response
----
....

[plantuml]
----
autonumber
Bob -> Alice : Authentication Request
Bob <- Alice : Authentication Response
----

==== Use Case Diagram

A link:https://plantuml.com/en/use-case-diagram[use case diagram] at its simplest is a representation of a user's interaction with the system that shows the relationship between the user and the different use cases in which the user is involved.

[source,asciidoc]
....
[plantuml]
----
User -> (Start)
User --> (Use the application) : A small label

:Main Admin: ---> (Use the application) : This is\nyet another\nlabel
----
....

[plantuml]
----
User -> (Start)
User --> (Use the application) : A small label

:Main Admin: ---> (Use the application) : This is\nyet another\nlabel
----

==== Class Diagram

A link:https://plantuml.com/en/class-diagram[class diagram] is a type of static structure diagram that describes the structure of a system by showing the system's classes, their attributes, operations (or methods), and the relationships among objects. 

[source,asciidoc]
....
[plantuml]
----
package "Classic Collections" #DDDDDD {
  Object <|-- ArrayList
}

package net.sourceforge.plantuml {
  Object <|-- Demo1
  Demo1 *- Demo2
}
----
....

[plantuml]
----
package "Classic Collections" #DDDDDD {
  Object <|-- ArrayList
}

package net.sourceforge.plantuml {
  Object <|-- Demo1
  Demo1 *- Demo2
}
----

==== Activity Diagram

link:https://plantuml.com/en/activity-diagram-beta[Activity diagrams] are graphical representations of workflows of stepwise activities and actions with support for choice, iteration and concurrency. 

[source,asciidoc]
....
[plantuml]
----
start

if (Graphviz installed?) then (yes)
  :process all\ndiagrams;
else (no)
  :process only
  __sequence__ and __activity__ diagrams;
endif

stop
----
....

[plantuml]
----
start

if (Graphviz installed?) then (yes)
  :process all\ndiagrams;
else (no)
  :process only
  __sequence__ and __activity__ diagrams;
endif

stop
----

==== Component Diagram

A link:https://plantuml.com/en/component-diagram[component diagram] depicts how components are wired together to form larger components or software systems.

[source,asciidoc]
....
[plantuml]
----
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}

node "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
}

database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}

[Another Component] --> [Folder 3]
[Folder 3] --> [Frame 4]
----
....

[plantuml]
----
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}

node "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
}

database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}

[Another Component] --> [Folder 3]
[Folder 3] --> [Frame 4]
----

==== State Diagram

link:https://plantuml.com/en/state-diagram[State diagrams] are used to give an abstract description of the behavior of a system. This behavior is represented as a series of events that can occur in one or more possible states. 

[source,asciidoc]
....
[plantuml]
----
[*] --> State1
State1 --> [*]
State1 : this is a string
State1 : this is another string

State1 -> State2
State2 --> [*]
----
....

[plantuml]
----
[*] --> State1
State1 --> [*]
State1 : this is a string
State1 : this is another string

State1 -> State2
State2 --> [*]
----

==== Object Diagram

An link:https://plantuml.com/en/object-diagram[object diagram] shows a complete or partial view of the structure of a modeled system at a specific time. 

[source,asciidoc]
....
[plantuml]
----
object Object01
object Object02
object Object03
object Object04
object Object05
object Object06
object Object07
object Object08

Object01 <|-- Object02
Object03 *-- Object04
Object05 o-- "4" Object06
Object07 .. Object08 : some labels
----
....

[plantuml]
----
object Object01
object Object02
object Object03
object Object04
object Object05
object Object06
object Object07
object Object08

Object01 <|-- Object02
Object03 *-- Object04
Object05 o-- "4" Object06
Object07 .. Object08 : some labels
----

==== Deployment Diagram

A link:https://plantuml.com/en/deployment-diagram[deployment diagram] models the physical deployment of artifacts on nodes.

[source,asciidoc]
....
[plantuml]
----
node node1
node node2
node node3
node node4
node node5
node1 -- node2 : label1
node1 .. node3 : label2
node1 ~~ node4 : label3
node1 == node5
----
....

[plantuml]
----
node node1
node node2
node node3
node node4
node node5
node1 -- node2 : label1
node1 .. node3 : label2
node1 ~~ node4 : label3
node1 == node5
----

==== Timing Diagram

A link:https://plantuml.com/en/timing-diagram[timing diagram] is a specific type of interaction diagram, where the focus is on timing constraints. 

[source,asciidoc]
....
[plantuml]
----
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing

@300
WB is Waiting
----
....

[plantuml]
----
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing

@300
WB is Waiting
----

==== Wireframe (Salt)

link:https://plantuml.com/en/salt[Salt] is a subproject included in PlantUML that may help you to design graphical interface. 

TIP: A Salt diagram must be started with the `salt` keyword.

[source,asciidoc]
....
[plantuml]
----
salt
{
  Just plain text
  [This is my button]
  ()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  [X] Checked box
  "Enter text here   "
  ^This is a droplist^
}
----
....

[plantuml]
----
salt
{
  Just plain text
  [This is my button]
  ()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  [X] Checked box
  "Enter text here   "
  ^This is a droplist^
}
----

==== Archimate Diagram

link:http://pubs.opengroup.org/architecture/archimate3-doc/[ArchiMate] is an open and independent enterprise architecture modeling language to support the description, analysis and visualization of architecture within and across business domains in an unambiguous way.
PlantUML provides a textual language for describing link:https://plantuml.com/en/archimate-diagram[archimate diagrams].

link:https://github.com/ebbypeter/Archimate-PlantUML[Archimate-PlantUML] defines marcros which simplify the creation of ArchiMate diagrams.
Because this is an extension to the language, it also also described in the <<Extended Diagram Types>> section at <<Archimate PlantUML>>.

[source,asciidoc]
....
[plantuml]
----
!define Junction_Or circle #black
!define Junction_And circle #whitesmoke

Junction_And JunctionAnd
Junction_Or JunctionOr

archimate #Technology "VPN Server" as vpnServerA <<technology-device>>

rectangle GO #lightgreen
rectangle STOP #red
rectangle WAIT #orange
GO -up-> JunctionOr
STOP -up-> JunctionOr
STOP -down-> JunctionAnd
WAIT -down-> JunctionAnd
----
....

[plantuml]
----
!define Junction_Or circle #black
!define Junction_And circle #whitesmoke

Junction_And JunctionAnd
Junction_Or JunctionOr

archimate #Technology "VPN Server" as vpnServerA <<technology-device>>

rectangle GO #lightgreen
rectangle STOP #red
rectangle WAIT #orange
GO -up-> JunctionOr
STOP -up-> JunctionOr
STOP -down-> JunctionAnd
WAIT -down-> JunctionAnd
----

==== Gantt Diagram

A link:https://plantuml.com/en/gantt-diagram[Gantt diagram] is a type of bar diagram that illustrates a project schedule.

The Gantt is described in natural language, using very simple sentences (subject-verb-complement). 

[source,asciidoc]
....
[plantuml]
----
Project starts the 13th of april 2020
[Prototype design] lasts 8 days
[Prototype design] is colored in Fuchsia/FireBrick
[Prototype design] is 40% completed
[Test prototype] starts at [Prototype design]'s end
[Test prototype] lasts 15 days
[Test prototype] is 0% completed
----
....

[plantuml]
----
Project starts the 13th of april 2020
[Prototype design] lasts 8 days
[Prototype design] is colored in Fuchsia/FireBrick
[Prototype design] is 40% completed
[Test prototype] starts at [Prototype design]'s end
[Test prototype] lasts 15 days
[Test prototype] is 0% completed
----

==== MindMap Diagram

A link:https://plantuml.com/en/mindmap-diagram[mind map] is a diagram used to visually organize information. A mind map is hierarchical and shows relationships among pieces of the whole.

TIP: A MindMap diagram must be started with the `@startmindmap` keyword and completed with the `@endmindmap` keyword.

[source,asciidoc]
....
[plantuml]
----
@startmindmap
* root node
** some first level node
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar
** another first level node
@endmindmap
----
....

[plantuml]
----
@startmindmap
* root node
** some first level node
***_ second level node
***_ another second level node
***_ foo
***_ bar
***_ foobar
** another first level node
@endmindmap
----

==== Work Breakdown Structure (WBS) Diagram

A link:https://plantuml.com/en/wbs-diagram[work-breakdown structure (WBS)] in project management and systems engineering, is a deliverable-oriented breakdown of a project into smaller components.

TIP: A WBS diagram must be started with the `@startwbs` keyword and completed with the `@endwbs` keyword.

[source,asciidoc]
....
[plantuml]
----
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
----
....

[plantuml]
----
@startwbs
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
----

==== Entity Relationship Diagram

An link:https://plantuml.com/en/ie-diagram[entity relationship diagram] describes interrelated things of interest in a specific domain of knowledge.

This is an extension to the existing <<Class Diagram>>.

[source,asciidoc]
....
[plantuml]
----
hide circle
skinparam linetype ortho

entity "Entity01" as e01 {
  *e1_id : number <<generated>>
  --
  *name : text
  description : text
}

entity "Entity02" as e02 {
  *e2_id : number <<generated>>
  --
  *e1_id : number <<FK>>
  other_details : text
}

entity "Entity03" as e03 {
  *e3_id : number <<generated>>
  --
  e1_id : number <<FK>>
  other_details : text
}

e01 ||..o{ e02
e01 |o..o{ e03
----
....

[plantuml]
----
hide circle
skinparam linetype ortho

entity "Entity01" as e01 {
  *e1_id : number <<generated>>
  --
  *name : text
  description : text
}

entity "Entity02" as e02 {
  *e2_id : number <<generated>>
  --
  *e1_id : number <<FK>>
  other_details : text
}

entity "Entity03" as e03 {
  *e3_id : number <<generated>>
  --
  e1_id : number <<FK>>
  other_details : text
}

e01 ||..o{ e02
e01 |o..o{ e03
----

=== Ditaa

link:http://ditaa.sourceforge.net/[Ditaa] interprets ascci art as a series of open and closed shapes, but it also uses special markup syntax to increase the possibilities of shapes and symbols that can be rendered.

TIP: A link:https://plantuml.com/en/ditaa[Ditaa diagram] must be started with the `ditaa` keyword.

[source,asciidoc]
....
[plantuml]
----
ditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
----
....

[source,asciidoc]
....
[plantuml]
----
ditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
----
....

=== DOT (Graphviz)

link:https://www.graphviz.org/[Graphviz] is open source graph visualization software. Graph visualization is a way of representing structural information as diagrams of abstract graphs and networks.
The graph description languange which is used by Graphviz is link:https://graphviz.gitlab.io/_pages/doc/info/lang.html[dot].

Since link:https://plantuml.com/en/dot[PlantUML uses DOT/Graphviz], it is possible to directly use DOT language.

[source,asciidoc]
....
[plantuml]
----
digraph G {
  subgraph cluster_0 {
    style=filled;
    color=lightgrey;
    node [style=filled,color=white];
    a0 -> a1 -> a2;
    label = "process #1";
  }
  subgraph cluster_1 {
    node [style=filled];
    b0 -> b1 -> b2;
    label = "process #2";
    color=blue
  }
  start -> a0;
  start -> b0;
  a1 -> b2;
  b1 -> a2;
  a2 -> a0;
  a2 -> end;
  b2 -> end;
  start [shape=Mdiamond];
  end [shape=Msquare];
}
----
....

[plantuml]
----
digraph G {
  subgraph cluster_0 {
    style=filled;
    color=lightgrey;
    node [style=filled,color=white];
    a0 -> a1 -> a2;
    label = "process #1";
  }
  subgraph cluster_1 {
    node [style=filled];
    b0 -> b1 -> b2;
    label = "process #2";
    color=blue
  }
  start -> a0;
  start -> b0;
  a1 -> b2;
  b1 -> a2;
  a2 -> a0;
  a2 -> end;
  b2 -> end;
  start [shape=Mdiamond];
  end [shape=Msquare];
}
----

==== Undirected Graphs

At its simplest, `dot` can be used to describe an `undirected graph`.

[source,asciidoc]
....
[plantuml]
----
graph graphname {
  a -- b -- c;
  b -- d;
}
----
....

[plantuml]
----
graph graphname {
  a -- b -- c;
  b -- d;
}
----

==== Directed Graphs

Similar to undirected graphs, `dot` can describe `directed graphs`, such as flowcharts and dependency trees.

[source,asciidoc]
....
[plantuml]
----
digraph graphname {
  a -> b -> c;
  b -> d;
}
----
....

[plantuml]
----
digraph graphname {
  a -> b -> c;
  b -> d;
}
----

==== Subgraphs

A graph can also have multiple `subgraphs`.

[source,asciidoc]
....
[plantuml]
----
digraph G {
  A; B; C
  subgraph Rel1 {
    edge [dir=none, color=red]
    A -> B -> C -> A
  }
  subgraph Rel2 {
    edge [color=blue]
    B -> C
    C -> A
  }
}
----
....

[plantuml]
----
digraph G {
  A; B; C
  subgraph Rel1 {
    edge [dir=none, color=red]
    A -> B -> C -> A
  }
  subgraph Rel2 {
    edge [color=blue]
    B -> C
    C -> A
  }
}
----

== Extended Diagram Types

Diagram types that are not directly supported by PlantUML, but made available through macros and additional steriotypes.

=== C4 PlantUML

The link:https://c4model.com/#coreDiagrams[C4 model] for software architecture is an "abstraction-first" approach to diagramming, based upon abstractions that reflect how software architects and developers think about and build software. C4 stands for context, containers, components, and code — a set of hierarchical diagrams that you can use to describe your software architecture at different zoom levels, each useful for different audiences.

link:https://github.com/RicardoNiepel/C4-PlantUML[C4-PlantUML] combines the benefits of PlantUML and the C4 model for providing a simple way of describing and communicate software architectures.

C4-PlantUML includes macros, stereotypes, and other goodies for creating C4 diagrams with PlantUML.

At the top of your `plantuml` block, you need to include the link:https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml[C4_Context.puml], link:https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml[C4_Container.puml] or link:https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml[C4_Component.puml] file found in the root of this repo.

----
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
----

For example a C4 Container diagram may be defined like this:

[source,asciidoc]
....
[plantuml]
----
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
  Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
----
....

[source,asciidoc]
....
[plantuml]
----
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
  Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
----
....

The link:https://github.com/RicardoNiepel/C4-PlantUML#supported-diagram-types[supported diagram types] are documented on the link:https://github.com/RicardoNiepel/C4-PlantUML#supported-diagram-types[C4-PlantUML] GitHub page.

=== Archimate PlantUML

link:http://pubs.opengroup.org/architecture/archimate3-doc/[ArchiMate] is an open and independent enterprise architecture modeling language to support the description, analysis and visualization of architecture within and across business domains in an unambiguous way.

PlantUML provides a textual language for describing link:https://plantuml.com/en/archimate-diagram[archimate diagrams] as described at <<Archimate Diagram>>.

link:https://github.com/ebbypeter/Archimate-PlantUML[Archimate-PlantUML] combines the benefits of PlantUML and ArchiMate for providing a simple way of creating and managing ArchiMate diagrams. The Archimate-PlantUML is a set of macros and other includes written on top of link:http://plantuml.com/archimate-diagram[PlantUML Archimate specification], with an aim to simplify the syntax for creating elements and defining relationships.

At the top of your `plantuml` block, you need to include the link:https://raw.githubusercontent.com/ebbypeter/Archimate-PlantUML/master/Archimate.puml[Archimate.puml] file.

----
!include https://raw.githubusercontent.com/ebbypeter/Archimate-PlantUML/master/Archimate.puml
----

For example a Archimate PlantUML diagram may be defined like this:

[source,asciidoc]
....
[plantuml]
----
!include https://raw.githubusercontent.com/ebbypeter/Archimate-PlantUML/v1.0.0/Archimate.puml

title Archimate Sample - Requirement & Application Services

Motivation_Requirement(ReqPayrollStandard, "Do Payroll with a standard system")
Motivation_Requirement(ReqBudgetPlanning, "Do budget planning within the ERP system")

Application_Service(ASPayroll,"Payroll Service")
Application_Service(ASBudgetPlanning,"Budget Planning Service")
Application_Component(ACSAPFinanceAccRec, "SAP Finance - Accounts Recievables")
Application_Component(ACSAPHR, "SAP Human Resources")
Application_Component(ACSAPFin, "SAP Finance")
Application_Component(ACSAP,"SAP") 

Rel_Realization_Up(ASPayroll, ReqPayrollStandard)
Rel_Realization_Up(ASBudgetPlanning, ReqBudgetPlanning)
Rel_Realization_Up(ACSAPFinanceAccRec, ASBudgetPlanning)
Rel_Realization_Up(ACSAPHR, ASPayroll)

Rel_Composition_Up(ACSAPFin, ACSAPFinanceAccRec)
Rel_Composition_Up(ACSAP, ACSAPHR)
Rel_Composition_Up(ACSAP, ACSAPFin)
----
....

[source,asciidoc]
....
[plantuml]
----
!include https://raw.githubusercontent.com/ebbypeter/Archimate-PlantUML/v1.0.0/Archimate.puml

title Archimate Sample - Requirement & Application Services

Motivation_Requirement(ReqPayrollStandard, "Do Payroll with a standard system")
Motivation_Requirement(ReqBudgetPlanning, "Do budget planning within the ERP system")

Application_Service(ASPayroll,"Payroll Service")
Application_Service(ASBudgetPlanning,"Budget Planning Service")
Application_Component(ACSAPFinanceAccRec, "SAP Finance - Accounts Recievables")
Application_Component(ACSAPHR, "SAP Human Resources")
Application_Component(ACSAPFin, "SAP Finance")
Application_Component(ACSAP,"SAP") 

Rel_Realization_Up(ASPayroll, ReqPayrollStandard)
Rel_Realization_Up(ASBudgetPlanning, ReqBudgetPlanning)
Rel_Realization_Up(ACSAPFinanceAccRec, ASBudgetPlanning)
Rel_Realization_Up(ACSAPHR, ASPayroll)

Rel_Composition_Up(ACSAPFin, ACSAPFinanceAccRec)
Rel_Composition_Up(ACSAP, ACSAPHR)
Rel_Composition_Up(ACSAP, ACSAPFin)
----
....

The link:https://github.com/ebbypeter/Archimate-PlantUML#usage[usage] is explained on the link:https://github.com/ebbypeter/Archimate-PlantUML#usage[Archimate-PlantUML] GitHub page.

== Unsupported Diagram Types

=== AsciiMath and JLaTeXMath

The link:https://plantuml.com/en/ascii-math[PlantUML documentation] states that math formulars can be expressed with link:http://asciimath.org/[AsciiMath] or link:https://github.com/opencollab/jlatexmath[JLaTeXMath] syntax.
However, GitLab does not support this PlantUML feature, and the following `plantuml` blocks therefore are rendered as plain text. 

[source,asciidoc]
....
[plantuml]
----
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
----
....

[source,asciidoc]
....
[plantuml]
----
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
----
....

[source,asciidoc]
....
[plantuml]
----
@startlatex
\sum_{i=0}^{n-1} (a_i + b_i^2)
@endlatex
----
....

[source,asciidoc]
....
[plantuml]
----
@startlatex
\sum_{i=0}^{n-1} (a_i + b_i^2)
@endlatex
----
....